"""add game query indexes

Revision ID: ab4ae2da2d6f
Revises: 986f0838a8f5
Create Date: 2026-08-28 15:19:43.868079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab4ae2da2d6f'
down_revision: Union[str, None] = '986f0838a8f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_games_skill_level_date', 'games', ['skill_level', 'game_date'], unique=False)
    op.create_index('ix_games_status_date_time', 'games', ['status', 'game_date', 'start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_games_status_date_time', table_name='games')
    op.drop_index('ix_games_skill_level_date', table_name='games')
    # ### end Alembic commands ###
